name: COMPAS compile test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths:
      - src/**
      - compas_python_utils/**
      - py_tests/**
      - .github/workflows/**
  push:
    branches:
      - dev
      -
# Ensures only the latest workflow run for the same branch is active, canceling any in-progress runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compas:
    env:
      ARTIFACT_NAME: detailedEvolutionPlot.png
      ARTIFACT_PATH: py_tests/test_artifacts

    name: Build COMPAS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: setup.py
      - name: Install TeXLive
        uses: teatimeguest/setup-texlive-action@v3
      - name: Install dependencies on ubuntu
        run: |
          cd misc/cicd-scripts
          chmod 755 linux-dependencies
          ./linux-dependencies
      - name: Build Compas
        run: |
          cd src && make -j $(nproc) -f Makefile
          ./COMPAS -v
      - name: Install python utils
        run: |
          pip install --upgrade pip
          pip install -e .[dev]
      - name: Run example COMPAS job
        run: |
          export COMPAS_EXECUTABLE_PATH=${GITHUB_WORKSPACE}/src/COMPAS
          cd ${GITHUB_WORKSPACE}/py_tests/test_data/
          chmod 755 run.sh
          cat run.sh
          ./run.sh
      - name: Run pytests
        run: |
          cd ${GITHUB_WORKSPACE}
          export COMPAS_ROOT_DIR=${GITHUB_WORKSPACE}
          jupyter-kernelspec list
          pytest --cov=compas_python_utils/ py_tests/ -m 'not webtest'
          pytest --cov=compas_python_utils/ --cov-append py_tests/ -m webtest
          ls py_tests/test_artifacts
          coverage html
          coverage-badge -o coverage_badge.svg -f
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: |
            htmlcov/
            coverage_badge.svg
      - name: Archive COMPAS detailed-evolution plot
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.ARTIFACT_NAME }}'
          path: '${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }}'
          if-no-files-found: error
      - name: Encode image to base64 # otherwise it wont be able to render i think...
        run: |
          BASE64_IMAGE=$(base64 -w 0 ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }})
          echo "BASE64_IMAGE=$BASE64_IMAGE" >> $GITHUB_ENV
      - name: Test Summary
        run: |
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- Compas Build: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Python Utils Installation: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Example COMPAS Job: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Pytest Execution: Success" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Detailed Evolution Plot" >> $GITHUB_STEP_SUMMARY
          echo "<img src="data:image/png;base64,${BASE64_IMAGE}" alt="Detailed Evolution Plot">" >> $GITHUB_STEP_SUMMARY
