name: Comment on Pull Request and Show Summary

on:
  workflow_run:
    workflows: ['COMPAS compile test']
    types:
      - completed

jobs:
  comment-and-summarize:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.name,
              run_id: ${{ github.event.workflow_run.id }},
            });
            const matchArtifact = artifacts.data.artifacts.find((artifact) => {
              return artifact.name == "detailedEvolutionPlot.png"
            });
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.name,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            const fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/detailedEvolutionPlot.zip', Buffer.from(download.data));

      - run: unzip detailedEvolutionPlot.zip

      - name: Get PR Number
        id: get-pr-number
        run: |
          PR_NUMBER=$(gh api /repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/pulls --jq '.[0].number')
          echo "PR_NUMBER=${PR_NUMBER:-null}" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        if: steps.get-pr-number.outputs.PR_NUMBER != 'null'
        with:
          issue-number: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
          comment-author: 'github-actions[bot]'

      - name: Update or Create Comment
        uses: peter-evans/create-or-update-comment@v3
        if: steps.get-pr-number.outputs.PR_NUMBER != 'null'
        with:
          issue-number: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            ## COMPAS Test Results
            
            The COMPAS compile test has completed successfully.
            
            ![Detailed Evolution Plot](detailedEvolutionPlot.png)
            
            [Link to workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})

      - name: Create Summary
        run: |
          echo "## COMPAS Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The COMPAS compile test has completed successfully." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "![Detailed Evolution Plot](detailedEvolutionPlot.png)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Compas Build: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Python Utils Installation: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Example COMPAS Job: Success" >> $GITHUB_STEP_SUMMARY
          echo "- Pytest Execution: Success" >> $GITHUB_STEP_SUMMARY
