name: Pre-commit Checks

on:
  push:
  pull_request:

# Ensures only the latest workflow run for the same branch is active, canceling any in-progress runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()


